"""The client-repo documentation contract — one definition, used by both the
scaffolder (`wf-scaffold-client-docs`) and the gate (`wf-client-docs-check`).

Why this exists. Every client repo's `docs/` tree was created by hand, and by
2026-07-28 no two of the five matched. Only `client-config.yml` and `INDEX.md`
existed everywhere. BLH-North had no work log, no cycle-logs and no
intake-archive at all, which means a cycle could run there with nowhere to record
what shipped. `bootstrap_config.py` generated exactly one file and nothing in the
engine knew the rest of the tree existed.

The rule this encodes: **every cycle must land in a durable, in-repo record.**
The intake ledger (`.drive-intake-state.json`) is a CI cache and is evictable;
`docs/intake-archive/` and `docs/seo-work-log.md` live in git and are the real
history. See BUG-010.

Adding a requirement here makes it mandatory fleet-wide, so add deliberately.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


@dataclass(frozen=True)
class DocSpec:
    path: str
    is_dir: bool
    required: bool
    why: str
    template: str = ""
    # A directory is only meaningful once it holds something; git will not track
    # an empty one. `keep` is the placeholder written to make it real.
    keep: str = ""


def _work_log(slug: str) -> str:
    return f"""# SEO Work Log — {slug}

Latest run at top. **Append-only — never edit or delete a past entry.**

Every cycle gets an entry here before it is called done. If it is not written
down it did not happen: this file is what the next person, and the next Claude,
reads to know what already shipped.

**Each entry states:** what shipped, the deploy commit, where the proofs live,
and what is still open.

---

## (no cycles logged yet)

This file was scaffolded by `wf-scaffold-client-docs`. Replace this section with
the first real cycle entry.
"""


def _progress(slug: str) -> str:
    """Matches the live format in northstar-landscaping-site / acme-roofing-site.

    NOT a rolling snapshot. It is an append-only run log, ONE dense line per
    pipeline run, oldest at top. Verified against the real files 2026-07-28.
    """
    return f"""# SEO Progress Log — {slug}

One line per pipeline run. Append-only.

---

(no runs logged yet — the first pipeline run appends its line below)
"""


def _index(slug: str) -> str:
    """Mirrors the section structure of the live docs/INDEX.md files."""
    return f"""# docs/ — Index (what lives where)

Client-specific knowledge and pipeline inputs for {slug}. The SEO/AEO automation
reads from here. No Meridian financials in this repo (retainers, team costs and
client-facing report PDFs stay out).

## Pipeline inputs (read by the automation)
- **`client-config.yml`** — master config: business info, NAP, locations and states,
  schema, and the **`forbidden_phrases:` block** (this client's standing content
  rules). Generate it with `wf-bootstrap-config`, never by hand from blank.
- **`banned-phrases.txt`** — optional companion ruleset, one pattern per line.
  `forbidden_sweep` reads this AND the config block, deduped.

## Client knowledge (targets, markets, company)
- **`client-asks/`** — client content decisions and preferences.
- **`intake-archive/YYYY-MM-DD/`** — content-team source material, per cycle.
  This is the durable record of what actually entered the pipeline.

## Work records (running logs the pipeline appends to)
- **`seo-work-log.md`** — running log of everything shipped, dated, newest at top.
- **`seo-progress.md`** — one line per pipeline run, append-only.
- **`seo-debt-backlog.md`** — outstanding SEO debt.
- **`cycle-logs/YYYY-MM-DD/`** — per-cycle post-mortems.
- **`gate-baseline.json`** — grandfathered legacy gate findings; only NEW findings block.

> **Not committed:** `audit-logs/` is regenerable and stays gitignored.
"""


def _debt(slug: str) -> str:
    return f"""# SEO Debt Backlog — {slug}

Known issues not yet fixed. One row per item. Close them or explain why not.

| ID | Issue | Severity | Found | Owner | Status |
|---|---|---|---|---|---|
| — | (none recorded yet) | — | — | — | — |
"""


DOC_SPECS: list[DocSpec] = [
    DocSpec("docs/client-config.yml", False, True,
            "Every gate reads this. Without it the suite cannot run.",
            template=""),  # generated by wf-bootstrap-config, never stubbed here
    DocSpec("docs/INDEX.md", False, True,
            "Tells a human (or a fresh Claude) what the rest of the tree is.",
            template="__index__"),
    DocSpec("docs/seo-work-log.md", False, True,
            "The append-only record of what shipped. The durable cycle history.",
            template="__work_log__"),
    DocSpec("docs/seo-progress.md", False, True,
            "Rolling snapshot of current state, so nobody re-derives it.",
            template="__progress__"),
    DocSpec("docs/cycle-logs", True, True,
            "Per-cycle post-mortems.",
            keep="# cycle-logs/\n\n"
                 "One folder per cycle, named `YYYY-MM-DD/` (the cycle close date).\n\n"
                 "**Standard file: `post-mortem.md`** — used by acme, Northstar and Crestline.\n"
                 "Add others alongside it as needed (e.g. `bottleneck-drilldown.md`).\n"),
    DocSpec("docs/intake-archive", True, True,
            "The team content actually ingested, per cycle. Durable counterpart to "
            "the evictable CI intake ledger.",
            keep="# intake-archive/\n\n"
                 "One folder per cycle, named `YYYY-MM-DD/` (the ingest date), holding the\n"
                 "team source material that actually entered the pipeline. This is the\n"
                 "durable record — the CI intake ledger is a cache and can be evicted.\n\n"
                 "**Standard file: `work-file.md`** — the converted monthly team work file.\n"
                 "Split into per-page files only when the team genuinely ships separate\n"
                 "documents. Historical folders use older names and are left alone.\n"),
    DocSpec("docs/seo-debt-backlog.md", False, False,
            "Known-but-unfixed issues. Optional, strongly recommended.",
            template="__debt__"),
]

REQUIRED = [d for d in DOC_SPECS if d.required]
OPTIONAL = [d for d in DOC_SPECS if not d.required]


def render(spec: DocSpec, slug: str) -> str:
    return {
        "__index__": _index, "__work_log__": _work_log,
        "__progress__": _progress, "__debt__": _debt,
    }[spec.template](slug)


def audit(repo: Path) -> tuple[list[DocSpec], list[DocSpec]]:
    """Return (missing_required, missing_optional) for a client repo checkout."""
    def present(d: DocSpec) -> bool:
        p = repo / d.path
        return p.is_dir() if d.is_dir else p.is_file()
    return ([d for d in REQUIRED if not present(d)],
            [d for d in OPTIONAL if not present(d)])


# ─── Cycle paths — the one place that knows where a cycle writes ───────────
#
# Every stage that writes into a client repo resolves its destination here, so
# the convention cannot drift again. Before this, the paths lived only in prose
# in INDEX.md and in whatever the last person happened to type, which is how
# five repos ended up with five different intake-archive naming styles.
#
# Canonical layout, verified against the live repos on 2026-07-28:
#
#   docs/intake-archive/<YYYY-MM-DD>/work-file.md   what the team handed us
#   docs/cycle-logs/<YYYY-MM-DD>/post-mortem.md     what happened
#   docs/seo-work-log.md                            append, newest at top
#   docs/seo-progress.md                            append, one line per run

INTAKE_ARCHIVE_FILE = "work-file.md"
POST_MORTEM_FILE = "post-mortem.md"


@dataclass(frozen=True)
class CyclePaths:
    """Resolved write destinations for one cycle of one client."""
    repo: Path
    cycle_date: str          # YYYY-MM-DD, the ingest/close date
    intake_dir: Path
    intake_file: Path
    cycle_log_dir: Path
    post_mortem: Path
    work_log: Path
    progress_log: Path

    def ensure(self) -> "CyclePaths":
        """Create the two dated directories. Never touches an existing file."""
        self.intake_dir.mkdir(parents=True, exist_ok=True)
        self.cycle_log_dir.mkdir(parents=True, exist_ok=True)
        return self


def cycle_paths(repo: Path, cycle_date: str) -> CyclePaths:
    """Resolve every write destination for a cycle. Pure — creates nothing.

    `cycle_date` must be YYYY-MM-DD. It is passed in rather than computed so a
    backfill writes into the cycle it belongs to, not into today.
    """
    if not _DATE_RE.match(cycle_date):
        raise ValueError(f"cycle_date must be YYYY-MM-DD, got {cycle_date!r}")
    intake_dir = repo / "docs" / "intake-archive" / cycle_date
    cycle_log_dir = repo / "docs" / "cycle-logs" / cycle_date
    return CyclePaths(
        repo=repo,
        cycle_date=cycle_date,
        intake_dir=intake_dir,
        intake_file=intake_dir / INTAKE_ARCHIVE_FILE,
        cycle_log_dir=cycle_log_dir,
        post_mortem=cycle_log_dir / POST_MORTEM_FILE,
        work_log=repo / "docs" / "seo-work-log.md",
        progress_log=repo / "docs" / "seo-progress.md",
    )


def append_work_log(repo: Path, entry: str) -> Path:
    """Prepend a dated entry to seo-work-log.md — newest at top, never destructive.

    The file is append-only by contract. This inserts after the header block and
    before the first existing entry, so history is never rewritten.
    """
    p = repo / "docs" / "seo-work-log.md"
    body = p.read_text() if p.is_file() else f"# SEO Work Log\n\nLatest run at top. **Append-only.**\n\n---\n"
    marker = "\n---\n"
    i = body.find(marker)
    if i == -1:
        return _write(p, body.rstrip() + "\n\n---\n\n" + entry.strip() + "\n")
    cut = i + len(marker)
    return _write(p, body[:cut] + "\n" + entry.strip() + "\n" + body[cut:])


def append_progress(repo: Path, line: str) -> Path:
    """Append one line to seo-progress.md. Oldest at top, matching the live format."""
    p = repo / "docs" / "seo-progress.md"
    body = p.read_text() if p.is_file() else "# SEO Progress Log\n\nOne line per pipeline run. Append-only.\n\n---\n"
    return _write(p, body.rstrip() + "\n\n" + line.strip() + "\n")


def _write(p: Path, text: str) -> Path:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return p
