#!/usr/bin/env python3
"""One place that reads HTML and sitemap XML.

There were eight `<loc>` regexes and four `<title>` regexes across this
codebase, and they did not agree with each other:

    <loc>\\s*([^<]+?)\\s*</loc>            orphan_check, parity_check   (IGNORECASE)
    <loc>\\s*([^<\\s][^<]*?)\\s*</loc>      measure                      (case-sensitive)
    <loc>\\s*([^<\\s]+)\\s*</loc>           baseline                     (case-sensitive)
    <loc>\\s*([^<\\s]+)\\s*</loc>           crawl                        (IGNORECASE)
    <loc>\\s*([^<\\s]+)                    validate     (no closing tag at all)
    <loc>https?://[^/]+(/[^<]*)</loc>    bootstrap_config             (path only)
    <loc>\\s*([^<\\s]+)\\s*</loc>           multipage                    (IGNORECASE)
    <loc>                                extra_checks       (counts open tags)

    <title[^>]*>([^<]+)</title>          audit_built, measure
    <title[^>]*>(.*?)</title>            seed_queries                 (I | S)
    <title[^>]*>([^<]*)</title>          crawl                        (IGNORECASE)

Eight answers to one question is eight chances to be wrong, and the ways they
were wrong were not cosmetic:

**Nobody decoded XML entities.** A sitemap MUST escape `&` as `&amp;`, so a
perfectly ordinary paginated URL is published as
`<loc>https://x.test/a?page=2&amp;sort=new</loc>`. Every one of the six handed
back the literal `&amp;`, which then got fetched (404), diffed against the route
list (mismatch), and reported as a broken or orphaned page. Same for `<title>`:
`Roof &amp; Gutter` was measured as 15 characters instead of 11 by the
title-length check, and two pages whose titles differ only in escaping compared
as different in the duplicate-title check.

**Half were case-sensitive** on a format where `<LOC>` is legal XML, and none
handled a namespace prefix (`<sm:loc>`) or a CDATA section, both of which appear
in sitemaps generated by real CMSes.

**`validate` had no closing tag**, so `<loc>https://x.test/a` inside a truncated
or malformed sitemap counted as a valid entry — a gate reporting a sitemap as
fine because it matched half a tag.

The functions here are deliberately still regex-based. Every parser in this
repo is stdlib-only by constraint, `xml.etree` refuses a sitemap with a stray
undeclared entity (which real ones have), and an HTML parser cannot be strict
about a `<title>` in a document that may be a fragment. What changes is that the
handling of the awkward cases is written once, tested once, and shared.
"""

from __future__ import annotations

import html as _html
import re

__all__ = ["sitemap_locs", "page_title", "inner_text", "decode_entities",
           "LOC_RE", "TITLE_RE"]

# `[^<]` rather than a URL character class: a `<` cannot appear inside XML
# character data, so it is the real terminator, and anything else the sitemap
# put there is content we should see rather than silently drop.
#
# `(?:[a-z][\w.-]*:)?` accepts a namespace prefix. `<url><loc>` is the common
# form, but a generator that declares the sitemap namespace with a prefix emits
# `<sm:loc>`, and half the old patterns silently matched zero URLs on those.
LOC_RE = re.compile(
    r"<(?:[a-z][\w.-]*:)?loc\b[^>]*>(.*?)</(?:[a-z][\w.-]*:)?loc\s*>",
    re.IGNORECASE | re.DOTALL,
)

TITLE_RE = re.compile(r"<title\b[^>]*>(.*?)</title\s*>", re.IGNORECASE | re.DOTALL)

_CDATA_RE = re.compile(r"<!\[CDATA\[(.*?)\]\]>", re.DOTALL)


def decode_entities(value: str) -> str:
    """`&amp;` -> `&`, `&#x2019;` -> `'`, and so on.

    `html.unescape` handles XML's five predefined entities plus the HTML named
    set, which is what a `<title>` needs and a superset of what a `<loc>` may
    legally contain. It leaves an unknown entity alone rather than raising,
    which is the behaviour we want on a malformed document: a page is better
    measured with one odd `&nosuch;` in its title than not measured at all.
    """
    return _html.unescape(value)


def _text(raw: str) -> str:
    """Element text: CDATA unwrapped, entities decoded, whitespace collapsed."""
    inner = _CDATA_RE.sub(lambda m: m.group(1), raw)
    return " ".join(decode_entities(inner).split())


def sitemap_locs(xml: str | None) -> list[str]:
    """Every `<loc>` in a sitemap or sitemap index, in document order.

    Empty entries are dropped: `<loc></loc>` names no URL, and letting it through
    produced an empty-string "page" that every downstream consumer then tried to
    fetch or compare. Duplicates are NOT dropped — a sitemap listing the same URL
    twice is a finding for the caller to report, not something to quietly tidy.
    """
    if not xml:
        return []
    out = []
    for raw in LOC_RE.findall(xml):
        value = _text(raw)
        if value:
            out.append(value)
    return out


def page_title(html: str | None) -> str | None:
    """The document `<title>`, decoded and whitespace-collapsed, or None.

    None and "" are different facts and both occur: no `<title>` element at all
    versus `<title></title>`, which is a page that declared a title and left it
    blank. Collapsing them loses the distinction the title-presence checks are
    built on, so an empty element returns "" and an absent one returns None.

    Only the FIRST `<title>` is returned. A document with two is a defect, but
    it is `onpage`'s defect to report; a reader asking for "the title" gets the
    one a browser would use.
    """
    if not html:
        return None
    m = TITLE_RE.search(html)
    if not m:
        return None
    return _text(m.group(1))


_TAG_RE = re.compile(r"<[^>]+>")


def inner_text(fragment: str | None) -> str:
    """Tag-stripped, entity-decoded, whitespace-collapsed text of a fragment.

    For elements whose content IS parsed markup — `<h1>Metal Roofing In
    <span>Austin</span></h1>` is the common modern layout, and its words are the
    page's real vocabulary. Deliberately not applied to `<title>`: title content
    is RCDATA, so a `<span>` in there is literal text a browser displays as
    typed, and stripping it would report a title the page does not have.
    """
    if not fragment:
        return ""
    return " ".join(decode_entities(_TAG_RE.sub(" ", fragment)).split())
