"""Source-code audit (pipeline/scanner/source_audit.py) — pure analyzer, offline."""
from pipeline.scanner.source_audit import analyze_source, fetch_repo_files, fetch_repo_tree


def test_tree_route_checks():
    tree = ["app/layout.tsx", "app/robots.ts", "app/sitemap.ts", "public/llms.txt", "middleware.ts"]
    by = {r["what"]: r for r in analyze_source({}, tree)}
    assert by["Source: robots.txt"]["severity"] == "ok"      # satisfied by app/robots.ts route
    assert by["Source: sitemap.xml"]["severity"] == "ok"     # satisfied by app/sitemap.ts route
    assert by["Source: llms.txt"]["severity"] == "ok"        # AEO
    assert by["Source: router"]["detail"] == "app router"
    assert by["Source: middleware"]["severity"] == "ok"


def test_tree_missing_seo_files():
    files = {"package.json": '{"dependencies":{"next":"14"}}'}
    by = {r["what"]: r for r in analyze_source(files, ["src/index.js", "package.json"])}
    assert by["Source: robots.txt"]["severity"] == "warn"
    assert by["Source: sitemap.xml"]["severity"] == "warn"
    assert by["Source: llms.txt"]["severity"] == "info"      # optional


def test_next_sitemap_dep_satisfies_sitemap():
    files = {"package.json": '{"dependencies":{"next":"14","next-sitemap":"4"}}'}
    by = {r["what"]: r for r in analyze_source(files, ["package.json"])}
    assert by["Source: sitemap.xml"]["severity"] == "ok"     # generated by next-sitemap


def test_fetch_repo_tree_parses_paths():
    def fake(url, token):
        assert "git/trees" in url
        return {"tree": [{"path": "app/robots.ts", "type": "blob"},
                         {"path": "public", "type": "tree"},
                         {"path": "public/llms.txt", "type": "blob"}]}
    paths = fetch_repo_tree("owner/name", "tok", fetch=fake)
    assert "app/robots.ts" in paths and "public/llms.txt" in paths
    assert "public" not in paths  # trees (dirs) excluded, blobs only


def test_fetch_repo_tree_local_skipped():
    assert fetch_repo_tree("/Users/both/site", "tok") == []
    assert fetch_repo_tree("", "tok") == []


def test_next_config_checks():
    files = {"package.json": '{"dependencies":{"next":"14"}}',
             "next.config.js": ("module.exports = { i18n: { locales: ['en','km'], defaultLocale: 'en' }, "
                                 "async headers() { return [] }, async redirects() { return [] } }")}
    by = {r["what"]: r for r in analyze_source(files, ["next.config.js", "package.json"])}
    assert by["Source: i18n"]["severity"] == "ok"
    assert by["Source: HTTP headers"]["severity"] == "ok"
    assert by["Source: redirects"]["severity"] == "ok"


def test_next_config_missing_headers_warn():
    files = {"package.json": '{"dependencies":{"next":"14"}}', "next.config.js": "module.exports = {}"}
    by = {r["what"]: r for r in analyze_source(files, ["next.config.js"])}
    assert by["Source: HTTP headers"]["severity"] == "warn"
    assert "Source: i18n" not in by  # only emitted when present


def test_no_next_config_no_config_rows():
    files = {"package.json": '{"dependencies":{"next":"14"}}'}
    by = {r["what"]: r for r in analyze_source(files, ["package.json"])}
    assert "Source: HTTP headers" not in by  # nothing to say without a config


def test_metadata_checks():
    layout = ("export const metadata = { metadataBase: new URL('https://x.com'), "
              "title: 'Home', description: 'd', openGraph: { title: 'Home' } }\n"
              "import { Inter } from 'next/font/google'")
    files = {"package.json": '{"dependencies":{"next":"14","@vercel/analytics":"1"}}',
             "app/layout.tsx": layout}
    by = {r["what"]: r for r in analyze_source(files, ["app/layout.tsx", "package.json"])}
    assert by["Source: metadataBase"]["severity"] == "ok"
    assert by["Source: default metadata"]["severity"] == "ok"
    assert by["Source: social tags"]["severity"] == "ok"
    assert by["Source: fonts"]["severity"] == "ok"
    assert by["Source: analytics"]["severity"] == "ok"


def test_commented_out_config_is_not_a_false_pass():
    files = {"package.json": '{"dependencies":{"next":"14"}}',
             "next.config.js": "module.exports = { /* i18n: { locales: [] }, */ } // async headers(){}",
             "app/layout.tsx": ("// export const metadata = { metadataBase: new URL('https://x') }\n"
                                "export default function L() { return null }")}
    by = {r["what"]: r for r in analyze_source(files, ["next.config.js", "app/layout.tsx"])}
    assert by["Source: HTTP headers"]["severity"] == "warn"   # headers() only in a comment
    assert "Source: i18n" not in by                            # i18n commented out
    assert by["Source: metadataBase"]["severity"] == "warn"    # metadataBase commented out
    assert by["Source: default metadata"]["severity"] == "warn"


def test_metadata_missing_warn():
    files = {"package.json": '{"dependencies":{"next":"14"}}',
             "app/layout.tsx": "export default function Layout() { return null }"}
    by = {r["what"]: r for r in analyze_source(files, ["app/layout.tsx"])}
    assert by["Source: metadataBase"]["severity"] == "warn"
    assert by["Source: default metadata"]["severity"] == "warn"
    assert "Source: analytics" not in by  # no analytics dep


def test_next_is_ssr_ok():
    files = {"package.json": '{"dependencies":{"next":"14.0.0","react":"18"}}'}
    by = {r["what"]: r for r in analyze_source(files)}
    assert by["Source: rendering"]["severity"] == "ok" and "Next.js" in by["Source: rendering"]["detail"]


def test_cra_is_csr_error():
    files = {"package.json": '{"dependencies":{"react-scripts":"5.0.0"}}'}
    by = {r["what"]: r for r in analyze_source(files)}
    assert by["Source: rendering"]["severity"] == "error"


def test_vite_spa_warns():
    files = {"package.json": '{"devDependencies":{"vite":"5.0.0"}}'}
    by = {r["what"]: r for r in analyze_source(files)}
    assert by["Source: rendering"]["severity"] == "warn"


def test_robots_and_sitemap_from_repo():
    files = {"package.json": '{"dependencies":{"next":"14"}}',
             "public/robots.txt": "User-agent: *", "public/sitemap.xml": "<urlset></urlset>"}
    by = {r["what"]: r for r in analyze_source(files)}
    assert by["Source: robots.txt"]["severity"] == "ok"
    assert by["Source: sitemap.xml"]["severity"] == "ok"


def test_local_path_repo_fetches_nothing():
    assert fetch_repo_files("/Users/both/site", "tok") == {}
    assert fetch_repo_files("", "tok") == {}


def test_fetch_uses_injected_getter():
    def fake(url, token):
        return '{"dependencies":{"next":"14"}}' if url.endswith("package.json") else None
    files = fetch_repo_files("owner/name", "tok", fetch=fake)
    assert "package.json" in files
    assert analyze_source(files)  # analyzes cleanly
