// Complete Catalog of 160 Specialized Tools & Automated Check Engines
// Sourced from Measure_Checks.docx and the REAI Intelligence Platform

export interface CatalogToolItem {
  id: string;
  name: string;
  category: "Competitive" | "Keywords" | "Backlinks" | "Technical" | "Trust & EEAT" | "Local & Reputation" | "AEO & AI" | "Remediation";
  engine: "DataForSEO" | "Core Crawler" | "Google CrUX" | "Claude AI" | "AEO Engine";
  desc: string;
  severity: "critical" | "warning" | "info" | "ok" | "tool";
  targetTab: string;
  subTab?: string;
}

export const ALL_PLATFORM_TOOLS: CatalogToolItem[] = [
  // ── 1. COMPETITIVE RESEARCH & DOMAIN INTELLIGENCE (10 Tools) ──
  {
    id: "cr-domain-overview",
    name: "Domain Overview Intelligence",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Comprehensive authority score, organic traffic trends, ranking keywords count, and SERP market position.",
    severity: "tool",
    targetTab: "Overview",
  },
  {
    id: "cr-traffic-analytics",
    name: "Traffic Analytics & Demographics",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Monthly visits, unique visitors, pages/visit, bounce rate, desktop vs mobile split, and geographic share.",
    severity: "tool",
    targetTab: "Traffic Analytics",
  },
  {
    id: "cr-organic-research",
    name: "Organic Search Research",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Google positions 1–100 distribution, intent classification, and SERP features won across search indices.",
    severity: "tool",
    targetTab: "Organic Research",
  },
  {
    id: "cr-keyword-gap",
    name: "Keyword Gap (3-Way Comparison)",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Side-by-side keyword overlap mapping missing, untapped, and weak keywords vs direct industry rivals.",
    severity: "tool",
    targetTab: "Keyword Gap",
  },
  {
    id: "cr-backlink-gap",
    name: "Backlink Gap & Opportunity Finder",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Discovers authoritative domains referring to multiple competitors where your domain has 0 backlinks.",
    severity: "tool",
    targetTab: "Backlink Gap",
  },
  {
    id: "cr-competitor-matrix",
    name: "SERP Competitors Positioning Matrix",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Automated discovery of domains competing for the exact same organic search queries.",
    severity: "tool",
    targetTab: "Organic Research",
  },
  {
    id: "cr-historical-trend",
    name: "Visibility & Historical Traffic Trend",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Multi-month organic search performance modeling and algorithmic volatility correlation.",
    severity: "tool",
    targetTab: "Overview",
  },
  {
    id: "cr-serp-features",
    name: "SERP Features Market Share",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Tracks wins across Featured Snippets, Knowledge Panels, Local Packs, People Also Ask, and Sitelinks.",
    severity: "tool",
    targetTab: "Organic Research",
  },
  {
    id: "cr-device-split",
    name: "Desktop vs Mobile Traffic Split",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Estimates device distribution and identifies mobile optimization conversion opportunities.",
    severity: "tool",
    targetTab: "Traffic Analytics",
  },
  {
    id: "cr-geo-distribution",
    name: "Geographic Market Share Analyzer",
    category: "Competitive",
    engine: "DataForSEO",
    desc: "Regional country-by-country breakdown of search demand, audience share, and local intent.",
    severity: "tool",
    targetTab: "Traffic Analytics",
  },

  // ── 2. KEYWORD RESEARCH & SERP LAB (9 Tools) ──
  {
    id: "kw-data-lab",
    name: "Keyword Data Lab",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Live Google search index rankings, search volume, intent categorization, and ranking positions.",
    severity: "tool",
    targetTab: "Keyword Data Lab",
  },
  {
    id: "kw-magic-tool",
    name: "Keyword Magic Tool",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Explore broad, phrase, exact, and question keyword variations from seed terms with KD% and CPC.",
    severity: "tool",
    targetTab: "Keyword Magic Tool",
  },
  {
    id: "kw-difficulty-analyzer",
    name: "Keyword Difficulty (KD%) Calculator",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Calculates the link equity and domain rating required to rank on Google Page 1.",
    severity: "tool",
    targetTab: "Keyword Magic Tool",
  },
  {
    id: "kw-intent-classifier",
    name: "Search Intent Automated Classifier",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Classifies terms into Informational, Navigational, Commercial, and Transactional search queries.",
    severity: "tool",
    targetTab: "Keyword Data Lab",
  },
  {
    id: "kw-question-miner",
    name: "Long-Tail Question Miner",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Isolates high-converting conversational questions ('how', 'what', 'where', 'best') for content briefs.",
    severity: "tool",
    targetTab: "Keyword Magic Tool",
  },
  {
    id: "kw-cpc-estimator",
    name: "Estimated CPC & Paid Value",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Google Ads cost-per-click estimates proving the monetary commercial value of ranking terms.",
    severity: "tool",
    targetTab: "Keyword Magic Tool",
  },
  {
    id: "kw-top3-tracker",
    name: "Top 3 SERP Ranking Monitor",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Tracks the highest conversion keywords occupying top 3 organic Google positions.",
    severity: "tool",
    targetTab: "Keyword Data Lab",
  },
  {
    id: "kw-page1-tracker",
    name: "Page 1 (Top 10) Organic Monitor",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Monitors keywords currently on Google first page that drive active traffic.",
    severity: "tool",
    targetTab: "Keyword Data Lab",
  },
  {
    id: "kw-page2-striking",
    name: "Page 2 Striking Distance Analyzer",
    category: "Keywords",
    engine: "DataForSEO",
    desc: "Identifies positions 11–20 terms that can quickly leap to page 1 with minor on-page optimizations.",
    severity: "tool",
    targetTab: "Organic Research",
  },

  // ── 3. LINK BUILDING & AUTHORITY AUDIT (7 Tools) ──
  {
    id: "lb-backlink-analytics",
    name: "Backlink Analytics Matrix",
    category: "Backlinks",
    engine: "DataForSEO",
    desc: "Authority score calculation, total backlink count, and referring domains growth rate.",
    severity: "tool",
    targetTab: "Data Lab & Backlinks",
  },
  {
    id: "lb-toxicity-audit",
    name: "Backlink Audit & Toxicity Dial",
    category: "Backlinks",
    engine: "DataForSEO",
    desc: "Assesses toxicity risk (0–100) from link farms, PBNs, and spam directories to avoid Google Penguin penalties.",
    severity: "tool",
    targetTab: "Backlink Audit",
  },
  {
    id: "lb-disavow-generator",
    name: "Google Disavow (.txt) Generator",
    category: "Backlinks",
    engine: "Core Crawler",
    desc: "Exports formatted disavow rules ready for submission to Google Search Console Disavow Links tool.",
    severity: "tool",
    targetTab: "Backlink Audit",
  },
  {
    id: "lb-anchor-diversity",
    name: "Anchor Text Diversity & Classification",
    category: "Backlinks",
    engine: "DataForSEO",
    desc: "Classifies anchors into Branded, Naked URL, Exact Match, Partial Match, and Generic to maintain natural ratios.",
    severity: "tool",
    targetTab: "Backlink Audit",
  },
  {
    id: "lb-tld-distribution",
    name: "Top-Level Domain (TLD) Profile",
    category: "Backlinks",
    engine: "DataForSEO",
    desc: "Analyzes distribution of referring extensions (.com, .org, .net, country TLDs).",
    severity: "tool",
    targetTab: "Backlink Audit",
  },
  {
    id: "lb-dofollow-ratio",
    name: "DoFollow vs NoFollow Ratio Scanner",
    category: "Backlinks",
    engine: "DataForSEO",
    desc: "Measures PageRank transmission equity across inbound link portfolio.",
    severity: "tool",
    targetTab: "Data Lab & Backlinks",
  },
  {
    id: "lb-broken-backlinks",
    name: "Broken Inbound Backlink Detector",
    category: "Backlinks",
    engine: "DataForSEO",
    desc: "Finds external links pointing to 404 dead pages that can be redirected to recover link equity.",
    severity: "warning",
    targetTab: "Data Lab & Backlinks",
  },

  // ── 4. DATAFORSEO SITE-WIDE CRAWL CHECKS (54 Checks from Measure_Checks.docx) ──
  { id: "dfs-4xx", name: "4xx Client Error Pages", category: "Technical", engine: "DataForSEO", desc: "Detects dead links, 404 Not Found, and 403 Forbidden pages during site crawl.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-5xx", name: "5xx Server Error Pages", category: "Technical", engine: "DataForSEO", desc: "Identifies 500 Internal Server Errors, 502 Bad Gateway, and 503 Service Unavailable pages.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-broken-pages", name: "Broken HTML Pages", category: "Technical", engine: "DataForSEO", desc: "Flags pages failing HTTP response verification.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-redirecting", name: "Redirecting Pages (301/302)", category: "Technical", engine: "DataForSEO", desc: "Tracks redirect chains causing crawl budget waste and TTFB latency.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-canon-broken", name: "Canonical Target Broken", category: "Technical", engine: "DataForSEO", desc: "Flags rel=canonical pointing to a 4xx/5xx dead URL, dropping indexing.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-canon-redir", name: "Canonical Points to Redirect", category: "Technical", engine: "DataForSEO", desc: "Identifies canonical tags pointing to intermediate 301/302 URLs.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-canon-recur", name: "Recursive Canonical Loop", category: "Technical", engine: "DataForSEO", desc: "Detects cyclic canonical references between URLs.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-redir-loop", name: "Redirect Loop (ERR_TOO_MANY_REDIRECTS)", category: "Technical", engine: "DataForSEO", desc: "Identifies endless redirect loops blocking crawlers and users.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-title", name: "Missing <title> Tag", category: "Technical", engine: "DataForSEO", desc: "Flags pages without an HTML title element in the <head>.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-title-long", name: "Title Tag Too Long (>60 characters)", category: "Technical", engine: "DataForSEO", desc: "Warns when title tags will be truncated in Google search results.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-title-short", name: "Title Tag Too Short (<30 characters)", category: "Technical", engine: "DataForSEO", desc: "Flags under-optimized titles missing target secondary keywords.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-dup-title", name: "Duplicate Title Tags Across Site", category: "Technical", engine: "DataForSEO", desc: "Finds multiple pages sharing identical titles, creating keyword cannibalization.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-desc", name: "Missing Meta Description", category: "Technical", engine: "DataForSEO", desc: "Flags pages lacking a meta description tag.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-dup-desc", name: "Duplicate Meta Tags", category: "Technical", engine: "DataForSEO", desc: "Detects conflicting or repeated meta description and viewport tags.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-irrel-desc", name: "Irrelevant Meta Description", category: "Technical", engine: "DataForSEO", desc: "Flags descriptions that fail to reflect the page body content.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-irrel-title", name: "Irrelevant Title Tag", category: "Technical", engine: "DataForSEO", desc: "Flags titles unrelated to main textual content.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-h1", name: "Missing <h1> Tag", category: "Technical", engine: "DataForSEO", desc: "Identifies pages missing a primary heading landmark.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-img-alt", name: "Images Missing Alt Attributes", category: "Technical", engine: "DataForSEO", desc: "Finds images missing alt text, impairing image SEO and accessibility.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-img-title", name: "Image Title Tag Missing", category: "Technical", engine: "DataForSEO", desc: "Notices image elements lacking descriptive title tags.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-fav", name: "Missing Favicon", category: "Technical", engine: "DataForSEO", desc: "Verifies presence of modern favicon and apple-touch-icon.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-doctype", name: "Missing HTML Doctype", category: "Technical", engine: "DataForSEO", desc: "Flags missing <!DOCTYPE html> causing Quirks Mode rendering.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-charset", name: "Missing Character Encoding", category: "Technical", engine: "DataForSEO", desc: "Ensures <meta charset='utf-8'> is declared early in the head.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-slow-load", name: "Slow Loading Page Time", category: "Technical", engine: "DataForSEO", desc: "Flags pages taking >3.0s total load time over high-speed connections.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-slow-ttfb", name: "Slow Server TTFB Response", category: "Technical", engine: "DataForSEO", desc: "Identifies time-to-first-byte exceeding 800ms.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-page-size", name: "Heavy Page Payload (>3MB)", category: "Technical", engine: "DataForSEO", desc: "Detects uncompressed assets inflating total payload size.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-render-block", name: "Render-Blocking CSS & JS Resources", category: "Technical", engine: "DataForSEO", desc: "Flags synchronous scripts blocking critical rendering path.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-low-text", name: "Low Text-to-HTML Ratio", category: "Technical", engine: "DataForSEO", desc: "Warns when page contains high code overhead with sparse text content.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-readability", name: "Low Readability / Flesch Score", category: "Technical", engine: "DataForSEO", desc: "Evaluates sentence complexity and reading ease grade level.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-placeholder", name: "Placeholder / Lorem Ipsum Text", category: "Technical", engine: "DataForSEO", desc: "Flags unremoved development placeholder copy on production URLs.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-deprec-html", name: "Deprecated HTML Tags", category: "Technical", engine: "DataForSEO", desc: "Finds obsolete HTML4 tags (<font>, <center>, <marquee>, <strike>).", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-flash", name: "Legacy Adobe Flash Content", category: "Technical", engine: "DataForSEO", desc: "Ensures no unplayable Flash objects exist on the page.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-frames", name: "HTML Frames & Iframe Nesting", category: "Technical", engine: "DataForSEO", desc: "Audits iframes for search crawler accessibility.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-broken-res", name: "Broken External Resources", category: "Technical", engine: "DataForSEO", desc: "Identifies failing CSS, font, script, or image resource calls.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-broken-links", name: "Broken Internal Links", category: "Technical", engine: "DataForSEO", desc: "Flags internal href links resulting in 404 or connection failures.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-rel-conflict", name: "Link Rel Conflict (nofollow/dofollow)", category: "Technical", engine: "DataForSEO", desc: "Checks for conflicting rel attributes on internal hyperlinks.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-orphan", name: "Orphaned Pages (No Inbound Links)", category: "Technical", engine: "DataForSEO", desc: "Detects pages in sitemap with 0 internal links from other pages.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-duplicate", name: "Duplicate Content Hash", category: "Technical", engine: "DataForSEO", desc: "Flags pages with >85% identical body content without canonicalization.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-mixed-links", name: "HTTPS → HTTP Insecure Links", category: "Technical", engine: "DataForSEO", desc: "Identifies links pointing to unencrypted HTTP targets.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-no-compress", name: "Missing Gzip / Brotli Compression", category: "Technical", engine: "DataForSEO", desc: "Verifies Content-Encoding headers for Brotli (br) or Gzip.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-seo-url", name: "SEO-Friendly Clean URLs", category: "Technical", engine: "DataForSEO", desc: "Checks for human-readable slugs without dynamic session IDs.", severity: "ok", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-https-ok", name: "HTTPS Protocol Enforcement", category: "Technical", engine: "DataForSEO", desc: "Validates SSL certificate and automatic HTTP to HTTPS 301 redirect.", severity: "ok", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-over-http", name: "Served Over Insecure HTTP", category: "Technical", engine: "DataForSEO", desc: "Flags pages accessible via raw unencrypted HTTP.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-struct-err", name: "Structured Data Syntax Errors", category: "Technical", engine: "DataForSEO", desc: "Detects broken JSON-LD syntax and missing required schema properties.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-title-words", name: "Title Tag Keyword Stuffing", category: "Technical", engine: "DataForSEO", desc: "Warns when title contains excessive repetition of single keywords.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-small-page", name: "Extremely Small Page (<500 bytes)", category: "Technical", engine: "DataForSEO", desc: "Identifies suspiciously thin or empty page responses.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-meta-kw", name: "Legacy Meta Keywords Present", category: "Technical", engine: "DataForSEO", desc: "Flags deprecated meta keywords tag ignored by modern search engines.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-canon-chain", name: "Canonical Chain (>2 hops)", category: "Technical", engine: "DataForSEO", desc: "Warns when canonicals point to URLs that themselves specify a canonical.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-miss-h2", name: "Missing <h2> Subheadings", category: "Technical", engine: "DataForSEO", desc: "Checks for semantic heading hierarchy dividing long content sections.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-meta-refresh", name: "Meta Refresh Redirect", category: "Technical", engine: "DataForSEO", desc: "Flags client-side <meta http-equiv='refresh'> instead of HTTP 301.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-dense-text", name: "Dense Text Walls (Missing Paragraphs)", category: "Technical", engine: "DataForSEO", desc: "Notices unbroken text blocks impairing mobile scannability.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-canon-present", name: "Canonical Tag Present", category: "Technical", engine: "DataForSEO", desc: "Confirms presence of canonical link specification.", severity: "ok", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-html5-doctype", name: "HTML5 Standard Doctype", category: "Technical", engine: "DataForSEO", desc: "Confirms standard <!DOCTYPE html> declaration.", severity: "ok", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-charset-ok", name: "UTF-8 Charset Validated", category: "Technical", engine: "DataForSEO", desc: "Confirms proper character encoding declaration.", severity: "ok", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "dfs-schema-present", name: "Schema.org Markup Present", category: "Technical", engine: "DataForSEO", desc: "Confirms discovery of structured data entities in DOM.", severity: "ok", targetTab: "Site Health & Audit", subTab: "all_checks" },

  // ── 5. DEEP ON-PAGE & SOURCE CODE AUDIT (28 Checks from onpage.py) ──
  { id: "op-charset", name: "DOM Charset Header Inspection", category: "Technical", engine: "Core Crawler", desc: "Verifies UTF-8 encoding is declared within first 1024 bytes.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-doctype", name: "HTML5 Root Doctype Verification", category: "Technical", engine: "Core Crawler", desc: "Checks for clean standards-mode doctype declaration.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-single-title", name: "Single <title> Tag Enforcement", category: "Technical", engine: "Core Crawler", desc: "Flags accidental multiple title tags created by React Helmet or Next.js head.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-single-desc", name: "Single Meta Description Enforcement", category: "Technical", engine: "Core Crawler", desc: "Ensures only one meta description tag is sent to search engines.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-mixed-content", name: "Mixed Active Content Scanner", category: "Technical", engine: "Core Crawler", desc: "Verifies no insecure http:// images, scripts, or stylesheets load on https://.", severity: "critical", targetTab: "On-Page SEO" },
  { id: "op-external-links", name: "External Link Safety (rel=noopener)", category: "Technical", engine: "Core Crawler", desc: "Checks target='_blank' links for rel='noopener noreferrer' security tags.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-render-scripts", name: "Render-Blocking Head Scripts", category: "Technical", engine: "Core Crawler", desc: "Detects synchronous script tags in <head> lacking defer or async attributes.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-img-dimensions", name: "Image Explicit Width & Height", category: "Technical", engine: "Core Crawler", desc: "Ensures <img> tags specify width/height to prevent Cumulative Layout Shift.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-deprecated", name: "Deprecated Markup Elimination", category: "Technical", engine: "Core Crawler", desc: "Audits for non-standard HTML elements.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-dom-size", name: "DOM Node Size (<1,500 Nodes)", category: "Technical", engine: "Core Crawler", desc: "Monitors overall DOM tree depth and node count for memory performance.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-link-volume", name: "Page Link Volume (<3,000 Links)", category: "Technical", engine: "Core Crawler", desc: "Ensures total links per page stays within crawl equity limits.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-hreflang", name: "hreflang Language Attribute", category: "Technical", engine: "Core Crawler", desc: "Validates ISO language codes in alternate link tags.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-semantic-main", name: "Semantic <main> Landmark", category: "Technical", engine: "Core Crawler", desc: "Checks for valid HTML5 <main> tag surrounding primary article content.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-url-len", name: "URL Slug Length (<100 characters)", category: "Technical", engine: "Core Crawler", desc: "Audits URL slug brevity for optimal SERP click-through rates.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-url-underscores", name: "URL Underscores Disallowance", category: "Technical", engine: "Core Crawler", desc: "Flags underscores (_) in URLs; Google recommends hyphens (-) as word separators.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-url-case", name: "URL Lowercase Consistency", category: "Technical", engine: "Core Crawler", desc: "Detects uppercase characters in URLs that can cause duplicate indexation.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-url-params", name: "URL Query Parameter Bloat", category: "Technical", engine: "Core Crawler", desc: "Audits dynamic URL parameters causing infinite crawler traps.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-subheadings", name: "Subheadings (H2/H3) Presence", category: "Technical", engine: "Core Crawler", desc: "Confirms proper structural breakdown of body text.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-heading-order", name: "Heading Hierarchy Order (H1→H2→H3)", category: "Technical", engine: "Core Crawler", desc: "Ensures headings do not skip levels (e.g. H1 directly to H4).", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-meta-refresh", name: "Meta Refresh Blocker", category: "Technical", engine: "Core Crawler", desc: "Guarantees no client-side redirects hijack the user experience.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-single-canon", name: "Single Canonical Tag Verification", category: "Technical", engine: "Core Crawler", desc: "Ensures only one canonical URL is defined per page.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-lorem", name: "Lorem Ipsum Content Detector", category: "Technical", engine: "Core Crawler", desc: "Scans for development dummy text left on live published pages.", severity: "critical", targetTab: "On-Page SEO" },
  { id: "op-flash", name: "Flash & Shockwave Blocker", category: "Technical", engine: "Core Crawler", desc: "Confirms modern mobile-friendly media standards.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-iframes", name: "Iframe Security & Sandboxing", category: "Technical", engine: "Core Crawler", desc: "Audits iframes for loading='lazy' and sandbox attributes.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-inline-styles", name: "Inline Style Overhead Audit", category: "Technical", engine: "Core Crawler", desc: "Flags excessive inline style attributes inflating HTML weight.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-empty-links", name: "Empty Anchor Tags (href='')", category: "Technical", engine: "Core Crawler", desc: "Finds broken dead links lacking destination URLs.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "op-meta-keywords", name: "Legacy Meta Keywords Removal", category: "Technical", engine: "Core Crawler", desc: "Advises removal of obsolete keyword tags that reveal strategy to competitors.", severity: "info", targetTab: "On-Page SEO" },
  { id: "op-apple-icon", name: "Apple Touch Icon Presence", category: "Technical", engine: "Core Crawler", desc: "Verifies high-resolution 180x180 icon for iOS bookmarking.", severity: "info", targetTab: "On-Page SEO" },

  // ── 6. CORE WEB VITALS & GOOGLE PERFORMANCE (3 Checks) ──
  { id: "perf-lcp", name: "Largest Contentful Paint (LCP < 2.5s)", category: "Technical", engine: "Google CrUX", desc: "Google ranking signal measuring main content render time.", severity: "critical", targetTab: "On-Page SEO" },
  { id: "perf-inp", name: "Interaction to Next Paint (INP < 200ms)", category: "Technical", engine: "Google CrUX", desc: "Google Core Web Vital measuring page responsiveness to user clicks/touches.", severity: "critical", targetTab: "On-Page SEO" },
  { id: "perf-cls", name: "Cumulative Layout Shift (CLS < 0.10)", category: "Technical", engine: "Google CrUX", desc: "Measures visual layout stability and prevents unexpected layout jumps.", severity: "critical", targetTab: "On-Page SEO" },

  // ── 7. TRUST, E-E-A-T & CONTENT QUALITY (9 Checks) ──
  { id: "eeat-author", name: "Author & Medical/Expertise Bio", category: "Trust & EEAT", engine: "Core Crawler", desc: "Audits for author bylines, credentials, and reviewer verification.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "eeat-contact", name: "Contact & Physical Trust Signals", category: "Trust & EEAT", engine: "Core Crawler", desc: "Checks for clear phone, address, email, and support pathways.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "eeat-policies", name: "Privacy Policy & Terms of Service", category: "Trust & EEAT", engine: "Core Crawler", desc: "Verifies footer links to privacy policy, terms, and regulatory compliance disclosures.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "eeat-social-proof", name: "Social Proof & Accreditation", category: "Trust & EEAT", engine: "Core Crawler", desc: "Scans for badges, certifications, and customer reviews.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "eeat-authoritativeness", name: "Domain Authoritativeness Signals", category: "Trust & EEAT", engine: "Core Crawler", desc: "Evaluates external citations, Wikipedia entity mentions, and press coverage.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "eeat-citations", name: "Citation-Ready Editorial Formatting", category: "Trust & EEAT", engine: "Core Crawler", desc: "Checks for source citations, footnotes, and outbound reference links.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "cnt-depth", name: "Content Word Depth (>500 words)", category: "Trust & EEAT", engine: "Core Crawler", desc: "Audits text volume against competitive averages for primary search topics.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "cnt-infogain", name: "Original Information-Gain Index", category: "Trust & EEAT", engine: "Core Crawler", desc: "Identifies unique data points, statistics, and tables not present on rival pages.", severity: "warning", targetTab: "On-Page SEO" },
  { id: "cnt-video", name: "VideoObject Schema & Rich Media", category: "Trust & EEAT", engine: "Core Crawler", desc: "Scans for embedded YouTube/HTML5 videos with schema for video SERP carousels.", severity: "info", targetTab: "Site Health & Audit", subTab: "all_checks" },

  // ── 8. AI & ANSWER ENGINES (AEO) (6 Checks) ──
  { id: "aeo-gptbot", name: "GPTBot / OpenAI Crawler Permissions", category: "AEO & AI", engine: "AEO Engine", desc: "Verifies robots.txt permits OpenAI search bots to index content.", severity: "critical", targetTab: "AI & AEO Lab" },
  { id: "aeo-claudebot", name: "ClaudeBot / Anthropic Permissions", category: "AEO & AI", engine: "AEO Engine", desc: "Verifies robots.txt allows Anthropic citation crawlers to read pages.", severity: "critical", targetTab: "AI & AEO Lab" },
  { id: "aeo-perplexity", name: "PerplexityBot Search Crawler Access", category: "AEO & AI", engine: "AEO Engine", desc: "Checks access for Perplexity AI conversational search engine.", severity: "critical", targetTab: "AI & AEO Lab" },
  { id: "aeo-local-schema", name: "LocalBusiness / Organization Schema", category: "AEO & AI", engine: "AEO Engine", desc: "Validates JSON-LD schema providing structured knowledge graph data to LLMs.", severity: "critical", targetTab: "AI & AEO Lab" },
  { id: "aeo-answer-first", name: "Answer-First Structural Layout", category: "AEO & AI", engine: "AEO Engine", desc: "Checks if direct concise answers appear in the first 100 words of subheadings.", severity: "warning", targetTab: "AI & AEO Lab" },
  { id: "aeo-llm-mentions", name: "LLM AI Citation Share Tracker", category: "AEO & AI", engine: "AEO Engine", desc: "Tracks brand citations across ChatGPT, Google Gemini, and Perplexity Search.", severity: "tool", targetTab: "AI & AEO Lab" },

  // ── 9. SITEMAP, HREFLANG & SOURCE CODE (11 Checks) ──
  { id: "map-valid", name: "XML Sitemap Syntax Validation", category: "Technical", engine: "Core Crawler", desc: "Ensures sitemap.xml is error-free and parseable by Googlebot.", severity: "critical", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "map-index", name: "Sitemap Index & Sub-Sitemaps", category: "Technical", engine: "Core Crawler", desc: "Verifies proper hierarchical sitemap index structure for large sites.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "map-size", name: "Sitemap File Size (<50MB / 50k URLs)", category: "Technical", engine: "Core Crawler", desc: "Confirms sitemap file does not exceed Google search engine size limits.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "map-scheme", name: "Sitemap HTTPS Scheme Enforcement", category: "Technical", engine: "Core Crawler", desc: "Verifies all URLs listed in sitemap use the secure https:// protocol.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "href-set", name: "hreflang Language Tags Declared", category: "Technical", engine: "Core Crawler", desc: "Verifies international language alternate tags are configured properly.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "href-bidirectional", name: "hreflang Bidirectional Return Links", category: "Technical", engine: "Core Crawler", desc: "Ensures alternate pages link back to each other, preventing ranking drops.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "href-xdefault", name: "hreflang x-default Fallback", category: "Technical", engine: "Core Crawler", desc: "Checks for x-default fallback landing page for unmatched languages.", severity: "warning", targetTab: "Site Health & Audit", subTab: "all_checks" },
  { id: "src-framework", name: "Source Code Framework Analyzer", category: "Remediation", engine: "Claude AI", desc: "Detects Next.js, Nuxt, Astro, or static HTML architecture for targeted fixes.", severity: "tool", targetTab: "Site Health & Audit", subTab: "remediation" },
  { id: "src-rendering", name: "SSR vs CSR Pre-rendering Verifier", category: "Remediation", engine: "Claude AI", desc: "Ensures crawler-critical SEO content is server-rendered, not hidden behind client JS.", severity: "critical", targetTab: "Site Health & Audit", subTab: "remediation" },
  { id: "src-robots", name: "robots.txt In-Repo Tracked Check", category: "Remediation", engine: "Claude AI", desc: "Verifies robots.txt is committed to source control repository.", severity: "warning", targetTab: "Site Health & Audit", subTab: "remediation" },
  { id: "src-sitemap", name: "sitemap.xml Automated Generation", category: "Remediation", engine: "Claude AI", desc: "Verifies sitemap is dynamically generated upon code builds or commits.", severity: "warning", targetTab: "Site Health & Audit", subTab: "remediation" },

  // ── 10. LOCAL SEO & REPUTATION (7 Checks) ──
  { id: "loc-gbp", name: "Google Business Profile (GBP) Discovery", category: "Local & Reputation", engine: "DataForSEO", desc: "Verifies linked Google Business Profile presence in Google Maps.", severity: "critical", targetTab: "Overview" },
  { id: "loc-reviews", name: "Customer Reviews & Rating Score", category: "Local & Reputation", engine: "DataForSEO", desc: "Monitors review quantity and average star rating across Google Local.", severity: "tool", targetTab: "Overview" },
  { id: "loc-category", name: "Primary GBP Business Category", category: "Local & Reputation", engine: "DataForSEO", desc: "Ensures primary Google Maps category matches core target keywords.", severity: "warning", targetTab: "Overview" },
  { id: "loc-nap", name: "NAP (Name/Address/Phone) Consistency", category: "Local & Reputation", engine: "DataForSEO", desc: "Validates NAP matches identically between website footer and Google Profile.", severity: "critical", targetTab: "Overview" },
  { id: "loc-claimed", name: "Claimed & Verified Status", category: "Local & Reputation", engine: "DataForSEO", desc: "Verifies profile ownership to prevent malicious edits.", severity: "warning", targetTab: "Overview" },
  { id: "rep-mentions", name: "Web Brand Mentions Tracker", category: "Local & Reputation", engine: "DataForSEO", desc: "Tracks unlinked brand mentions across news, forums, and blogs for outreach.", severity: "tool", targetTab: "Data Lab & Backlinks" },
  { id: "rep-sentiment", name: "Mention Sentiment Classification", category: "Local & Reputation", engine: "DataForSEO", desc: "Classifies sentiment (Positive, Neutral, Negative) of brand coverage.", severity: "info", targetTab: "Data Lab & Backlinks" },

  // ── 11. CLAUDE CODE AUTONOMOUS REMEDIATION (4 Tools) ──
  { id: "rem-claude-fix", name: "Claude Code Autonomous Auto-Repair", category: "Remediation", engine: "Claude AI", desc: "Applies code patches directly into repository to resolve SEO & schema issues.", severity: "tool", targetTab: "Site Health & Audit", subTab: "remediation" },
  { id: "rem-diff-generator", name: "Git Diffstat & Patch Inspector", category: "Remediation", engine: "Claude AI", desc: "Previews precise git diff changes before committing to production branches.", severity: "tool", targetTab: "Site Health & Audit", subTab: "remediation" },
  { id: "rem-brancher", name: "Auto-Branching & PR Automation", category: "Remediation", engine: "Claude AI", desc: "Automatically creates dedicated GitHub branches for safe review.", severity: "tool", targetTab: "Site Health & Audit", subTab: "remediation" },
  { id: "rem-gatekeeper", name: "Preflight Gatekeeper & Regression Test", category: "Remediation", engine: "Claude AI", desc: "Validates fixes post-deploy to guarantee 0 regressions against baseline.", severity: "tool", targetTab: "Site Health & Audit", subTab: "remediation" },
];
